---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/womgvumy/doctorclinic.kajabian.com/
    - /bin/cp -R * $DEPLOYPATH












































































































































































































































ooii32jjai39jfjkjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjkkhihijoejiruekekudeyrvfwcwset,gggmtrgtgtgutmggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggguttir